DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS machines;

CREATE TABLE machines (
    MACHINEID TEXT PRIMARY KEY,
    OCCUPANCY_STATUS TEXT NOT NULL CHECK (OCCUPANCY_STATUS IN ('vacant', 'occupied')),
    CONDITION_STATUS TEXT NOT NULL CHECK (CONDITION_STATUS IN ('normal', 'broken')),
    LAST_CONDITION_UPDATE TEXT,
    LAST_CONDITION_REASON TEXT,

     -- SC6: problem timestamps for issue tracking.
    PROBLEM_REPORTED_AT TEXT,
    PROBLEM_RESOLVED_AT TEXT
);

CREATE TABLE sessions (
    SESSIONID INTEGER PRIMARY KEY,
    MACHINEID TEXT NOT NULL,
    FIRSTNAME TEXT NOT NULL,
    LASTNAME TEXT NOT NULL,
    PHONENUMBER TEXT NOT NULL CHECK (length(PHONENUMBER) = 10),

     -- SC2/SC6: session timestamps for expected end and delay calculations.
    TIMEIN TEXT NOT NULL,
    EXPECTED_END TEXT NOT NULL,

    STATUS TEXT NOT NULL CHECK (STATUS IN ('active', 'picked_up')),
    FINISH_SMS_STATUS TEXT,
    FINISH_SMS_SENT_AT TEXT,
    VERIFICATION_CODE TEXT,

    -- SC4/SC6: pickup completion time and delay minutes.
    TIMEOUT TEXT,
    DELAY_MIN INTEGER NOT NULL DEFAULT 0 CHECK (DELAY_MIN >= 0),

    FOREIGN KEY (MACHINEID) REFERENCES machines(MACHINEID)
);
