CREATE TABLE sessions (
    SESSIONID INTEGER PRIMARY KEY,
    MACHINEID TEXT NOT NULL,
    FIRSTNAME TEXT NOT NULL,
    LASTNAME TEXT NOT NULL,
    PHONENUMBER TEXT NOT NULL CHECK (length(PHONENUMBER) = 10),
    TIMEIN TEXT NOT NULL,
    STATUS TEXT NOT NULL CHECK (STATUS IN ('active', 'picked_up'))
);