DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS machines;

CREATE TABLE machines (
    MACHINEID TEXT PRIMARY KEY,
    OCCUPANCY_STATUS TEXT NOT NULL CHECK (OCCUPANCY_STATUS IN ('vacant', 'occupied')),
    CONDITION_STATUS TEXT NOT NULL CHECK (CONDITION_STATUS IN ('normal', 'broken')),
    LAST_CONDITION_UPDATE TEXT,
    LAST_CONDITION_REASON TEXT
);

CREATE TABLE sessions (
    SESSIONID INTEGER PRIMARY KEY,
    MACHINEID TEXT NOT NULL,
    FIRSTNAME TEXT NOT NULL,
    LASTNAME TEXT NOT NULL,
    PHONENUMBER TEXT NOT NULL CHECK (length(PHONENUMBER) = 10),
    TIMEIN TEXT NOT NULL,
    STATUS TEXT NOT NULL CHECK (STATUS IN ('active', 'picked_up')),
    FINISH_SMS_STATUS TEXT,
    FINISH_SMS_SENT_AT TEXT,
    VERIFICATION_CODE TEXT,
    TIMEOUT TEXT,
    FOREIGN KEY (MACHINEID) REFERENCES machines(MACHINEID)
);
